import { Router } from 'express';
import authRouter from './auth.route';
import attributeRouter from './attribute.route';
import categoryRouter from './category.route';
import productRouter from './product.route';
import voucherRouter from './voucher.route';
import invoiceRouter from './invoice.route';
import customerRouter from './customer.route';
import orderRouter from './order.route';
import importProductRouter from './import-product.route';
import preOrderImportRouter from './pre-order-import.route';
import staffRouter from './staff.route';
import profileRequest from './profile-request.route';
import reportTicketRouter from './report-ticket.route';
import returnTicketRouter from './return-ticket.route';
import adminAccountRouter from './admin-account.route';
import aiConversationRouter from './ai-conversation.route';
import notificationRouter from './notification.route';
const router = Router();

router.use('/auth', authRouter);
router.use('/attributes', attributeRouter);
router.use('/categories', categoryRouter);
router.use('/products', productRouter);
router.use('/vouchers', voucherRouter);
router.use('/invoices', invoiceRouter);
router.use('/customers', customerRouter);
router.use('/orders', orderRouter);
router.use('/import-products', importProductRouter);
router.use('/pre-order-imports', preOrderImportRouter);
router.use('/staff', staffRouter);
router.use('/profile-requests', profileRequest);
router.use('/report-tickets', reportTicketRouter);
router.use('/return-tickets', returnTicketRouter);
router.use('/admin-accounts', adminAccountRouter);
router.use('/ai-conversations', aiConversationRouter);
router.use('/notifications', notificationRouter);
export default router;
