export enum ReturnTicketStatus {
    PENDING = 'PENDING',
    IN_PROGRESS = 'IN_PROGRESS',
    CANCEL = 'CANCEL',
    REJECTED = 'REJECTED',
    APPROVED = 'APPROVED',
    DELIVERING = 'DELIVERING',
    RETURNED = 'RETURNED',
    FAIL_RETURNED = 'FAIL_RETURNED',
}
