export const emittedEvent = {
  notification: {
    RECEIVE_INVOICE_CREATE: "RECEIVE_INVOICE_CREATE",
    RECEIVE_ASSIGN_ORDER: "RECEIVE_ASSIGN_ORDER",
    RECEIVE_ASSIGN_INVOICE: "RECEIVE_ASSIGN_INVOICE",
    RECEIVE_COMPLETE_INVOICE: "RECEIVE_COMPLETE_INVOICE"
  },
};
export const listenedEvent = {
  notification: {
    INVOICE_CREATE: "INVOICE_CREATE", // khi customer tạo invoice ->
    ASSIGN_ORDER: "ASSIGN_ORDER",
    ASSIGN_INVOICE: "ASSIGN_INVOICE",
    COMPLETE_INVOICE: "COMPLETE_INVOICE"
  }
}